services:
  nginx:
    image: nginx:alpine
    container_name: todo_nginx
    ports:
      - "80:80"
      - "8443:8443"
      - "443:443"
    volumes:
      - ./todo-laravel:/var/www/laravel
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php
      - mysql
      - nextjs
    networks:
      - todo_network

  certbot:
    image: certbot/certbot
    container_name: todo_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - todo_network

  php:
    build:
      context: .
      dockerfile: ./Docker/php8.3/Dockerfile
    container_name: todo_laravel
    volumes:
      - ./todo-laravel:/var/www/laravel
      - ./Docker/php8.3/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - todo_network


  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Sarajevo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - todo_network
     

  nextjs:
    build:
      context: ./todo-next
      dockerfile: Dockerfile
    container_name: todo_next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://todo:8443/api
    volumes:
      - ./todo-next:/app
      - /app/node_modules
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mysql_data: